### ISSUE TITLE
App support link in iTunes goes to socksuccess

### ISSUE THREAD

**Issue by appalive** [deltapp/iOS#18]

**Comment by saetia** [comment]
hah, i’ll fix that

**Comment by saetia** [comment]
never use www. when entering a url:

http://ivebeendelt.com http://ivebeendelt.com/ and http://www.ivebeendelt.com http://www.ivebeendelt.com/

**Comment by appalive** [comment]
It's weird. When I'm In the App Store and I click on app support that socksuccess store comes up.

Regards,

Frank

P.S Please excuse the brevity and typos. This e-mail sent from my iPhone.

On Mar 23, 2015, at 5:10 PM, Joel Glovacki <notifications@github.com<mailto:notifications@github.com>> wrote:

never use www. when entering a url:

http://ivebeendelt.com http://ivebeendelt.com/ and http://www.ivebeendelt.com http://www.ivebeendelt.com/

> On Mar 23, 2015, at 5:05 PM, appalive <notifications@github.com<mailto:notifications@github.com>> wrote:
> 
> ## 
> 
> Reply to this email directly or view it on GitHub https://github.com/deltapp/iOS/issues/18.

##

**Comment by saetia** [comment]
i know, that’s because you used http://www.ivebeendelt.com instead of http://ivebeendelt.com http://ivebeendelt.com/.

**Comment by appalive** [comment]
Aaaaah. I'll fix it in iTunesconnect. We got almost 30 downloads Saturday and early Sunday morning.

Regards,

Frank

P.S Please excuse the brevity and typos. This e-mail sent from my iPhone.

On Mar 23, 2015, at 6:03 PM, Joel Glovacki <notifications@github.com<mailto:notifications@github.com>> wrote:

i know, that's because you used http://www.ivebeendelt.com instead of http://ivebeendelt.com http://ivebeendelt.com/.

> On Mar 23, 2015, at 5:55 PM, appalive <notifications@github.com<mailto:notifications@github.com>> wrote:
> 
> It's weird. When I'm In the App Store and I click on app support that socksuccess store comes up.
> 
> Regards,
> 
> Frank
> 
> P.S Please excuse the brevity and typos. This e-mail sent from my iPhone.
> 
> On Mar 23, 2015, at 5:10 PM, Joel Glovacki <notifications@github.com<mailto:notifications@github.com>mailto:notifications@github.com> wrote:
> 
> never use www. when entering a url:
> 
> http://ivebeendelt.com http://ivebeendelt.com/ and http://www.ivebeendelt.com http://www.ivebeendelt.com/
> 
> > On Mar 23, 2015, at 5:05 PM, appalive <notifications@github.com<mailto:notifications@github.com>mailto:notifications@github.com> wrote:
> > 
> > ## 
> > 
> > Reply to this email directly or view it on GitHub https://github.com/deltapp/iOS/issues/18.
> 
> ## 
> 
> ## Reply to this email directly or view it on GitHubhttps://github.com/deltapp/iOS/issues/18#issuecomment-85225843.
> 
> Reply to this email directly or view it on GitHub https://github.com/deltapp/iOS/issues/18#issuecomment-85238963.

##
